jdk: oraclejdk8
language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26
    - extra-android-m2repository
    - extra-google-m2repository

notifications:
 email: false

script:
 - ./gradlew build 2>&1 > /dev/null
 - curl --upload-file ./app/build/outputs/apk/debug/app-debug.apk https://transfer.sh
