jdk: oraclejdk8
language: android
android:
  components:
    - tools
    - platform-tools
    - tools # Bug with Travis - ensure BT 25 is installed (https://github.com/travis-ci/docs-travis-ci-com/issues/779)
    - build-tools-26.0.2
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository

notifications:
 email: false

script:
 - ./gradlew build
